function expr = odeMotifs(t,in2,in3)
%odeMotifs
%    EXPR = odeMotifs(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    28-Apr-2026 13:43:22

h1 = in2(10,:);
param5 = in3(:,1);
param6 = in3(:,2);
param7 = in3(:,3);
param8 = in3(:,4);
param9 = in3(:,5);
x1 = in2(1,:);
x2 = in2(4,:);
x3 = in2(7,:);
y1 = in2(2,:);
y2 = in2(5,:);
y3 = in2(8,:);
z1 = in2(3,:);
z2 = in2(6,:);
z3 = in2(9,:);
t2 = -x2;
t3 = -x3;
expr = [-y1-z1;x1+param5.*y1;param6-z1.*(param7-x1);-h1+t2+x1-y2-z2;x2+param5.*y2;param6-z2.*(param7+t2);t3+x2-y3-z3;x3+param5.*y3;param6-z3.*(param7+t3);-param8.*(t2+x1)-h1.*param9];
end
