function expr = odeMotifChain(t,in2,in3)
%odeMotifChain
%    EXPR = odeMotifChain(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    28-Apr-2026 13:43:02

param1 = in3(:,1);
param2 = in3(:,2);
param3 = in3(:,3);
param4 = in3(:,4);
x1 = in2(1,:);
x2 = in2(4,:);
x3 = in2(7,:);
y1 = in2(2,:);
y2 = in2(5,:);
y3 = in2(8,:);
z1 = in2(3,:);
z2 = in2(6,:);
z3 = in2(9,:);
t2 = -y1;
t3 = -y2;
t4 = -y3;
expr = [-param1.*(t2+x1);t2+x1.*(param2-z1);-param3.*z1+x1.*y1;-param1.*(t3+x2)+param4.*(x1-x2);t3+x2.*(param2-z2);-param3.*z2+x2.*y2;-param1.*(t4+x3)+param4.*(x2-x3);t4+x3.*(param2-z3);-param3.*z3+x3.*y3];
end
