function expr = odeMotifsChain(t,in2,in3)
%odeMotifsChain
%    EXPR = odeMotifsChain(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-Apr-2026 13:27:12

h1 = in2(10,:);
param21 = in3(:,1);
param22 = in3(:,2);
param23 = in3(:,3);
param24 = in3(:,4);
param25 = in3(:,5);
x1 = in2(1,:);
x2 = in2(4,:);
x3 = in2(7,:);
y1 = in2(2,:);
y2 = in2(5,:);
y3 = in2(8,:);
z1 = in2(3,:);
z2 = in2(6,:);
z3 = in2(9,:);
t2 = h1.*param25;
t3 = -h1;
t4 = -x2;
t5 = -x3;
t6 = -y2;
t7 = -y3;
t8 = -z2;
t9 = -z3;
t10 = -t2;
expr = [-y1-z1;x1+param21.*y1;param22-z1.*(param23-x1);t3+t4+t6+t8+x1;t3+t6+x2+y1+param21.*y2;param22+t3+t8+z1+t8.*(param23+t4);t5+t7+t9+x2;t7+x3+y2+param21.*y3;param22+t9+z2+t9.*(param23+t5);t10-param24.*(t4+x1);t10-param24.*(t6+y1);t10-param24.*(t8+z1)];
end
