function expr = odeVariational(t,in2,in3)
%odeVariational
%    EXPR = odeVariational(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-Apr-2026 13:18:00

Y1 = in2(4,:);
Y2 = in2(5,:);
Y3 = in2(6,:);
Y4 = in2(7,:);
Y5 = in2(8,:);
Y6 = in2(9,:);
Y7 = in2(10,:);
Y8 = in2(11,:);
Y9 = in2(12,:);
Y10 = in2(13,:);
param11 = in3(:,1);
param12 = in3(:,2);
x = in2(1,:);
y = in2(2,:);
z = in2(3,:);
t2 = Y1.*2.0;
t3 = x-5.7e+1./1.0e+1;
expr = [-y-z;x+y./5.0;t3.*z+1.0./5.0;-Y2-Y3+Y10-t2;Y1+Y2./5.0;Y3.*t3+Y1.*z;Y4.*-2.0-Y5-Y6-Y10+t2;Y4+Y5./5.0;Y6.*t3+Y4.*z;Y7.*-2.0-Y8-Y9+t2;Y7+Y8./5.0;Y9.*t3+Y7.*z;-Y1.*param12-Y10.*param11];
end
